name: backup_database
description: Sistema de backup autom√°tico para SQL Server e Sybase ASA
publish_to: "none"
version: 2.1.3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  auto_updater: ^1.0.0
  brasil_fields: ^1.18.0
  crypto: ^3.0.7
  cron: ^0.6.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.29.0
  encrypt: ^5.0.3
  file_picker: ^10.3.7
  fluent_ui: ^4.13.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2
  ffi: ^2.1.3
  ftpconnect: ^2.0.10
  get_it: ^9.1.1
  google_fonts: ^6.2.1
  googleapis: ^15.0.0
  http: ^1.2.2
  intl: ^0.20.2
  logger: ^2.6.2
  mailer: ^6.6.0
  oauth2_client: ^4.2.1
  package_info_plus: ^8.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  result_dart: ^2.1.1
  shared_preferences: ^2.3.3
  sqlite3_flutter_libs: ^0.5.40
  timezone: ^0.10.1
  tray_manager: ^0.5.2
  url_launcher: ^6.3.1
  uuid: ^4.5.2
  win32: ^5.15.0
  window_manager: ^0.5.1
  xml: ^6.5.0
  zard: ^0.0.24

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/favicon.ico
    - assets/icons/icon-512-maskable.png
    - assets/icons/icon-512-dark.svg
    - assets/icons/icon-512-embedded.svg
    - assets/image/
    - assets/image/apple-touch-icon.png
    - assets/image/icon-192.png
    - assets/image/icon-512-maskable.png

flutter_launcher_icons:
  image_path: "assets/icons/icon-512-maskable.png"
  android: false
  windows:
    generate: true
    image_path: "assets/icons/icon-512-maskable.png"
    icon_size: 256
